# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 14:08
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tba_camps', '0017_inscription_motif_rem'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='caf',
            field=models.CharField(choices=[(b'O', b'Oui'), (b'N', b'Non')], default=b'N', max_length=1, verbose_name=b"Je b\xc3\xa9n\xc3\xa9ficie d'une aide CAF ou VACAF"),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='train',
            field=models.DecimalField(choices=[(Decimal('0.00'), b'Pas de suppl\xc3\xa9ment'), (Decimal('160.00'), b'Aller-retour tarif normal (160\xe2\x82\xac)'), (Decimal('80.00'), b'Aller-retour moins de 12 ans (80\xe2\x82\xac)'), (Decimal('80.00'), b'Aller tarif normal (80\xe2\x82\xac)'), (Decimal('40.00'), b'Aller moins de 12 ans (40\xe2\x82\xac)'), (Decimal('80.00'), b'Retour tarif normal (80\xe2\x82\xac)'), (Decimal('40.00'), b'Retour moins de 12 ans (40\xe2\x82\xac)')], decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name=b'Suppl\xc3\xa9ment train depuis Paris (inclut les navettes aller et retour)'),
        ),
    ]
