# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 17:33
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tba_camps', '0019_formule_taxe_gym'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formule',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name=b'Prix formule'),
        ),
        migrations.AlterField(
            model_name='formule',
            name='taxe',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name=b'Taxe m\xc3\xa9nage'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='assurance',
            field=models.DecimalField(choices=[(Decimal('0.00'), b'Non'), (Decimal('6.00'), 'Avec assurance (6\u20ac)')], decimal_places=2, default=Decimal('6.00'), max_digits=10, verbose_name=b'Assurance annulation'),
        ),
    ]
