# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tba_camps', '0020_auto_20151231_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='mode_solde',
            field=models.CharField(blank=True, default=b'', max_length=1023, verbose_name=b'R\xc3\xa8glement solde'),
        ),
    ]
