# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-08 17:32
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tba_camps', '0025_auto_20160107_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='train',
            field=models.DecimalField(choices=[(Decimal('0.000'), b'Pas de suppl\xc3\xa9ment'), (Decimal('160.000'), b'Aller-retour tarif normal (160\xe2\x82\xac)'), (Decimal('80.000'), b'Aller-retour moins de 12 ans (80\xe2\x82\xac)'), (Decimal('80.001'), b'Aller tarif normal (80\xe2\x82\xac)'), (Decimal('40.000'), b'Aller moins de 12 ans (40\xe2\x82\xac)'), (Decimal('80.002'), b'Retour tarif normal (80\xe2\x82\xac)'), (Decimal('40.001'), b'Retour moins de 12 ans (40\xe2\x82\xac)')], decimal_places=3, default=Decimal('0.000'), max_digits=10, verbose_name=b'Suppl\xc3\xa9ment train depuis Paris (inclut les navettes aller et retour)'),
        ),
    ]
