# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-26 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tba_camps', '0026_auto_20160408_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='num_chambre',
            field=models.CharField(blank=True, default=b'', max_length=10, verbose_name=b'Num\xc3\xa9ro chambre'),
        ),
        migrations.AddField(
            model_name='inscription',
            name='type_chambre',
            field=models.CharField(blank=True, choices=[(b'Chambre', b'Chambre'), (b'Chalet', b'Ch\xc3\xa2let')], default=b'', max_length=20, verbose_name=b'Type chambre'),
        ),
    ]
