# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 23:26
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import tba_camps.models


class Migration(migrations.Migration):

    dependencies = [
        ('tba_camps', '0027_auto_20160627_0152'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='club',
            field=models.CharField(blank=True, max_length=255, verbose_name='Club'),
        ),
        migrations.AlterField(
            model_name='formule',
            name='affiche_accompagnateur',
            field=models.BooleanField(default=False, verbose_name='Opt. accompagnateur'),
        ),
        migrations.AlterField(
            model_name='formule',
            name='affiche_assurance',
            field=models.BooleanField(default=True, verbose_name='Opt. assurance'),
        ),
        migrations.AlterField(
            model_name='formule',
            name='affiche_chambre',
            field=models.BooleanField(default=False, verbose_name="Opt. 'chambre avec'"),
        ),
        migrations.AlterField(
            model_name='formule',
            name='affiche_hebergement',
            field=models.BooleanField(default=False, verbose_name='Opt. hébergement'),
        ),
        migrations.AlterField(
            model_name='formule',
            name='affiche_mode',
            field=models.BooleanField(default=True, verbose_name='Opt. mode réglément'),
        ),
        migrations.AlterField(
            model_name='formule',
            name='affiche_navette',
            field=models.BooleanField(default=True, verbose_name='Opt. navette'),
        ),
        migrations.AlterField(
            model_name='formule',
            name='affiche_train',
            field=models.BooleanField(default=False, verbose_name='Opt. train'),
        ),
        migrations.AlterField(
            model_name='formule',
            name='cotisation',
            field=models.DecimalField(decimal_places=2, default=15, max_digits=10, verbose_name='Cotisation TBA'),
        ),
        migrations.AlterField(
            model_name='formule',
            name='groupe',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='formule',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix formule'),
        ),
        migrations.AlterField(
            model_name='formule',
            name='publique',
            field=models.BooleanField(default=True, verbose_name='Tout publique'),
        ),
        migrations.AlterField(
            model_name='formule',
            name='taxe',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Taxe ménage'),
        ),
        migrations.AlterField(
            model_name='formule',
            name='taxe_gym',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Taxe gymnase'),
        ),
        migrations.AlterField(
            model_name='hebergement',
            name='commentaire',
            field=models.TextField(blank=True, verbose_name="Commentaire affiché à l'inscription"),
        ),
        migrations.AlterField(
            model_name='hebergement',
            name='managed',
            field=models.BooleanField(default=False, verbose_name="Envoyer fiche d'inscription à TBA"),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='accompagnateur',
            field=models.CharField(blank=True, max_length=255, verbose_name="Nom de l'accompagnateur"),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='adr_parrain',
            field=models.CharField(blank=True, max_length=255, verbose_name='Adresse parrain'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='assurance',
            field=models.DecimalField(choices=[(Decimal('0.00'), 'Non'), (Decimal('6.00'), 'Avec assurance (6€)')], decimal_places=2, default=Decimal('6.00'), max_digits=10, verbose_name='Assurance annulation'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='caf',
            field=models.CharField(choices=[('O', 'Oui'), ('N', 'Non')], default='N', max_length=1, verbose_name="Je bénéficie d'une aide CAF ou VACAF"),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='certificat',
            field=tba_camps.models.FileField(blank=True, null=True, upload_to='', verbose_name='Certificat médical'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='certificat_snail',
            field=models.BooleanField(default=False, verbose_name='Certificat médical reçu'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='chambre',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='En chambre avec'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='cp',
            field=models.CharField(max_length=10, verbose_name='Code postal'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date inscription'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='date_valid',
            field=models.DateField(blank=True, null=True, verbose_name='Date validation'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='email',
            field=models.EmailField(blank=True, max_length=255, verbose_name='Adresse email (des parents)'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='etat',
            field=models.CharField(choices=[('P', 'Pré-inscription'), ('V', 'Validé'), ('C', 'Complet'), ('A', 'Annulé')], default='V', max_length=1, verbose_name="État de l'inscription"),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='fiche_hotel',
            field=tba_camps.models.FileField(blank=True, null=True, upload_to='', verbose_name='Réservation hébergement'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='fiche_hotel_snail',
            field=models.BooleanField(default=False, verbose_name='Réservation hébergement reçue'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='fiche_inscr',
            field=tba_camps.models.FileField(blank=True, null=True, upload_to='', verbose_name="Fiche d'inscription"),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='fiche_inscr_snail',
            field=models.BooleanField(default=False, verbose_name="Fiche d'inscription reçue"),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='fiche_sanit',
            field=tba_camps.models.FileField(blank=True, null=True, upload_to='', verbose_name='Fiche sanitaire'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='fiche_sanit_snail',
            field=models.BooleanField(default=False, verbose_name='Fiche sanitaire reçue'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='licence',
            field=models.CharField(blank=True, max_length=31, verbose_name='Numéro de licence'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='lieu',
            field=models.CharField(max_length=255, verbose_name='Lieu de naissance'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='mode',
            field=models.CharField(blank=True, default='', max_length=1023, verbose_name='Mode de règlement'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='mode_solde',
            field=models.CharField(blank=True, default='', max_length=1023, verbose_name='Règlement solde'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='motif',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Motif du supplément'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='motif_rem',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Motif de la remise'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='naissance',
            field=models.DateField(verbose_name='Date de naissance'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='navette_a',
            field=models.DecimalField(choices=[(Decimal('0.00'), 'Non'), (Decimal('6.00'), 'Oui (6€)')], decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Navette aller'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='navette_r',
            field=models.DecimalField(choices=[(Decimal('0.00'), 'Non'), (Decimal('6.00'), 'Oui (6€)')], decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Navette retour'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='nom_parrain',
            field=models.CharField(blank=True, max_length=255, verbose_name='NOM Prénom parrain'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='num_chambre',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Numéro chambre'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='parrain',
            field=models.BooleanField(default=False, verbose_name='Parrain'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='pays',
            field=models.CharField(default='France', max_length=255),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='prix_hebergement',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix hébergement'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='remise',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Remise'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='sexe',
            field=models.CharField(choices=[('H', 'Homme'), ('F', 'Femme')], default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='supplement',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Supplément'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='taille',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(300), django.core.validators.MinValueValidator(30)], verbose_name='Taille (cm)'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='tel',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Numéro invalide', regex='^\\+?[\\d -\\.]{10,}$')], verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='train',
            field=models.DecimalField(choices=[(Decimal('0.000'), 'Pas de supplément'), (Decimal('160.000'), 'Aller-retour tarif normal (160€)'), (Decimal('80.000'), 'Aller-retour moins de 12 ans (80€)'), (Decimal('80.001'), 'Aller tarif normal (80€)'), (Decimal('40.000'), 'Aller moins de 12 ans (40€)'), (Decimal('80.002'), 'Retour tarif normal (80€)'), (Decimal('40.001'), 'Retour moins de 12 ans (40€)')], decimal_places=3, default=Decimal('0.000'), max_digits=10, verbose_name='Supplément train depuis Paris (inclut les navettes aller et retour)'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='type_chambre',
            field=models.CharField(blank=True, choices=[('Chambre', 'Chambre'), ('Chalet', 'Châlet')], default='', max_length=20, verbose_name='Type chambre'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='venu',
            field=models.CharField(choices=[('O', 'Oui'), ('N', 'Non')], default=0, max_length=1, verbose_name='Je suis déjà venu à Superdévoluy'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='notif',
            field=models.BooleanField(default=True, verbose_name='Reçoit une notification à chaque action des utilisateurs'),
        ),
        migrations.AlterField(
            model_name='semaine',
            name='commentaire',
            field=models.CharField(blank=True, max_length=255, verbose_name='Commentaire affiché'),
        ),
        migrations.AlterField(
            model_name='semaine',
            name='debut',
            field=models.DateField(unique=True, verbose_name='Début de la semaine'),
        ),
        migrations.AlterField(
            model_name='semaine',
            name='fermer',
            field=models.BooleanField(default=False, verbose_name='Inscriptions fermées'),
        ),
        migrations.AlterField(
            model_name='semaine',
            name='places',
            field=models.IntegerField(default=0, verbose_name='Nombre de places'),
        ),
    ]
