# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 01:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tba_camps', '0029_auto_20161203_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hebergement',
            name='managed',
            field=models.CharField(choices=[('I', 'Géré par TBA'), ('M', 'Géré par TBA, payement séparé'), ('E', 'Réservé par le client')], default='I', max_length=1, verbose_name='Mode réservation'),
        ),
    ]
