# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tba_camps', '0030_auto_20161213_0208'),
    ]

    operations = [
        migrations.AddField(
            model_name='formule',
            name='adulte',
            field=models.BooleanField(default=False, verbose_name='Adulte'),
        ),
    ]
