# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 01:08
from __future__ import unicode_literals

from django.db import migrations
import tba_camps.models


class Migration(migrations.Migration):

    dependencies = [
        ('tba_camps', '0031_formule_adulte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='fiche_inscr',
            field=tba_camps.models.FileField(blank=True, null=True, upload_to='', verbose_name="Bulletin d'inscription"),
        ),
    ]
