# Generated by Django 2.0 on 2017-12-26 01:13

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import tba_camps.models


class Migration(migrations.Migration):

    dependencies = [
        ('tba_camps', '0033_auto_20161219_2345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Adresse email')),
                ('secret', models.SlugField(blank=True, editable=False, max_length=22)),
                ('titre', models.CharField(blank=True, choices=[('M', 'Mr'), ('F', 'Mme')], max_length=1, null=True)),
                ('nom', models.CharField(max_length=255, null=True)),
                ('prenom', models.CharField(max_length=255, null=True)),
                ('adresse', models.TextField(null=True)),
                ('cp', models.CharField(max_length=10, null=True, verbose_name='Code postal')),
                ('ville', models.CharField(max_length=255, null=True)),
                ('pays', models.CharField(default='France', max_length=255, null=True)),
                ('tel', models.CharField(max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Numéro invalide', regex='^\\+?[\\d -\\.]{10,}$')], verbose_name='Téléphone')),
                ('mode', models.CharField(blank=True, default='', max_length=1023, verbose_name='Mode de règlement')),
                ('mode_solde', models.CharField(blank=True, default='', max_length=1023, verbose_name='Règlement solde')),
                ('etat', models.CharField(choices=[('0', 'Email non confirmée'), ('1', 'Pré-inscription incomplète'), ('P', 'Pré-inscription'), ('V', 'Validé'), ('C', 'Complet'), ('A', 'Annulé')], default='V', max_length=1, verbose_name='État du dossier')),
                ('acompte', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('remise', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Remise')),
                ('motif_rem', models.CharField(blank=True, default='', max_length=255, verbose_name='Motif de la remise')),
                ('supplement', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Supplément')),
                ('motif', models.CharField(blank=True, default='', max_length=255, verbose_name='Motif du supplément')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date inscription')),
                ('date_valid', models.DateField(blank=True, null=True, verbose_name='Date validation')),
                ('prix_hebergement', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix hébergement')),
                ('fiche_hotel', tba_camps.models.FileField(blank=True, null=True, upload_to='', verbose_name='Réservation hébergement')),
                ('fiche_hotel_snail', models.BooleanField(default=False, verbose_name='Réservation hébergement reçue')),
                ('notes', models.TextField(blank=True, default='')),
                ('caf', models.CharField(choices=[('O', 'Oui'), ('N', 'Non')], default='N', max_length=1, verbose_name="Je bénéficie d'une aide CAF ou VACAF")),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stagiaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('sexe', models.CharField(choices=[('H', 'Homme'), ('F', 'Femme')], default=0, max_length=1)),
                ('naissance', models.DateField(verbose_name='Date de naissance')),
                ('lieu', models.CharField(max_length=255, verbose_name='Lieu de naissance')),
                ('venu', models.CharField(choices=[('O', 'Oui'), ('N', 'Non')], default=0, max_length=1, verbose_name='Je suis déjà venu à Superdévoluy')),
                ('taille', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(300), django.core.validators.MinValueValidator(30)], verbose_name='Taille (cm)')),
                ('licence', models.CharField(blank=True, max_length=31, verbose_name='Numéro de licence')),
                ('club', models.CharField(blank=True, max_length=255, verbose_name='Club')),
                ('accompagnateur', models.CharField(blank=True, max_length=255, verbose_name="Nom de l'accompagnateur")),
                ('train', models.DecimalField(choices=[(Decimal('0.000'), 'Pas de supplément'), (Decimal('160.000'), 'Aller-retour tarif normal (160€)'), (Decimal('80.000'), 'Aller-retour moins de 12 ans (80€)'), (Decimal('80.001'), 'Aller tarif normal (80€)'), (Decimal('40.000'), 'Aller moins de 12 ans (40€)'), (Decimal('80.002'), 'Retour tarif normal (80€)'), (Decimal('40.001'), 'Retour moins de 12 ans (40€)')], decimal_places=3, default=Decimal('0.000'), max_digits=10, verbose_name='Supplément train depuis Paris (inclut les navettes aller et retour)')),
                ('chambre', models.CharField(blank=True, default='', max_length=255, verbose_name='En chambre avec')),
                ('type_chambre', models.CharField(blank=True, choices=[('Chambre', 'Chambre'), ('Chalet', 'Châlet')], default='', max_length=20, verbose_name='Type chambre')),
                ('num_chambre', models.CharField(blank=True, default='', max_length=10, verbose_name='Numéro chambre')),
                ('navette_a', models.DecimalField(choices=[(Decimal('0.00'), 'Non'), (Decimal('6.00'), 'Oui (6€)')], decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Navette aller')),
                ('navette_r', models.DecimalField(choices=[(Decimal('0.00'), 'Non'), (Decimal('6.00'), 'Oui (6€)')], decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Navette retour')),
                ('assurance', models.DecimalField(choices=[(Decimal('0.00'), 'Non'), (Decimal('6.00'), 'Avec assurance (6€)')], decimal_places=2, default=Decimal('6.00'), max_digits=10, verbose_name='Assurance annulation')),
                ('parrain', models.BooleanField(default=False, verbose_name='Parrain')),
                ('nom_parrain', models.CharField(blank=True, max_length=255, verbose_name='NOM Prénom parrain')),
                ('adr_parrain', models.CharField(blank=True, max_length=255, verbose_name='Adresse parrain')),
                ('fiche_inscr', tba_camps.models.FileField(blank=True, null=True, upload_to='', verbose_name="Bulletin d'inscription")),
                ('fiche_inscr_snail', models.BooleanField(default=False, verbose_name="Fiche d'inscription reçue")),
                ('fiche_sanit', tba_camps.models.FileField(blank=True, null=True, upload_to='', verbose_name='Fiche sanitaire')),
                ('fiche_sanit_snail', models.BooleanField(default=False, verbose_name='Fiche sanitaire reçue')),
                ('certificat', tba_camps.models.FileField(blank=True, null=True, upload_to='', verbose_name='Certificat médical')),
                ('certificat_snail', models.BooleanField(default=False, verbose_name='Certificat médical reçu')),
                ('notes', models.TextField(blank=True, default='')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tba_camps.Dossier')),
                ('formule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tba_camps.Formule')),
                ('hebergement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tba_camps.Hebergement')),
                ('semaines', models.ManyToManyField(to='tba_camps.Semaine')),
            ],
        ),
        migrations.RemoveField(
            model_name='inscription',
            name='formule',
        ),
        migrations.RemoveField(
            model_name='inscription',
            name='hebergement',
        ),
        migrations.RemoveField(
            model_name='inscription',
            name='semaines',
        ),
        migrations.DeleteModel(
            name='Inscription',
        ),
    ]
