# Generated by Django 2.0 on 2017-12-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tba_camps', '0034_auto_20171226_0213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stagiaire',
            name='notes',
        ),
        migrations.AddField(
            model_name='stagiaire',
            name='niveau',
            field=models.CharField(choices=[('B', 'Débutant'), ('D', 'Départemental'), ('R', 'Régional'), ('F', 'Championnat de France')], default='B', max_length=1, verbose_name='Niveau de pratique'),
            preserve_default=False,
        ),
    ]
