# Generated by Django 2.0 on 2017-12-31 15:12

from django.db import migrations, models
import tba_camps.models


class Migration(migrations.Migration):

    dependencies = [
        ('tba_camps', '0035_auto_20171227_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stagiaire',
            name='fiche_inscr',
        ),
        migrations.RemoveField(
            model_name='stagiaire',
            name='fiche_inscr_snail',
        ),
        migrations.AddField(
            model_name='stagiaire',
            name='auth_paren',
            field=tba_camps.models.FileField(blank=True, null=True, upload_to='', verbose_name='Autorisation parentale'),
        ),
        migrations.AddField(
            model_name='stagiaire',
            name='auth_paren_snail',
            field=models.BooleanField(default=False, verbose_name='Autorisation parentale reçue'),
        ),
    ]
