# Generated by Django 2.0 on 2018-01-02 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tba_camps', '0037_auto_20180102_0553'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='semaines',
            field=models.ManyToManyField(to='tba_camps.Semaine'),
        ),
    ]
