# Generated by Django 2.0 on 2018-01-03 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tba_camps', '0038_dossier_semaines'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hebergement',
            options={'verbose_name': 'Hébergement'},
        ),
    ]
