# Generated by Django 2.0 on 2018-01-11 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tba_camps', '0040_auto_20180110_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='formule',
            name='acompte',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10, verbose_name='Acompte'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dossier',
            name='assurance',
            field=models.BooleanField(default=True, verbose_name='Assurance annulation'),
        ),
    ]
