# Generated by Django 2.0 on 2018-01-15 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tba_camps', '0041_auto_20180111_0201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hebergement',
            options={'ordering': ('order',), 'verbose_name': 'Hébergement'},
        ),
        migrations.AlterField(
            model_name='dossier',
            name='semaines',
            field=models.ManyToManyField(blank=True, to='tba_camps.Semaine'),
        ),
        migrations.AlterField(
            model_name='semaine',
            name='formule_complet',
            field=models.ManyToManyField(blank=True, to='tba_camps.Formule'),
        ),
        migrations.AlterField(
            model_name='semaine',
            name='hbgt_complet',
            field=models.ManyToManyField(blank=True, to='tba_camps.Hebergement'),
        ),
    ]
