# Generated by Django 2.0.1 on 2018-02-04 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tba_camps', '0044_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='titre',
            field=models.CharField(default='Hello', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='etat',
            field=models.CharField(choices=[('0', 'Email non confirmée'), ('1', 'Pré-inscription incomplète'), ('P', 'Pré-inscription'), ('V', 'Validé'), ('C', 'Complet'), ('A', 'Annulé')], max_length=1, verbose_name='Envoyer aux dossiers'),
        ),
        migrations.AlterField(
            model_name='message',
            name='formule',
            field=models.ManyToManyField(blank=True, to='tba_camps.Formule'),
        ),
        migrations.AlterField(
            model_name='message',
            name='hebergement',
            field=models.ManyToManyField(blank=True, to='tba_camps.Hebergement'),
        ),
    ]
