# Generated by Django 2.0.1 on 2018-02-25 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tba_camps', '0045_auto_20180204_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossier',
            name='date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date inscription'),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='email',
            field=models.EmailField(db_index=True, max_length=255, unique=True, verbose_name='Adresse email'),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='etat',
            field=models.CharField(choices=[('0', 'Email non confirmée'), ('1', 'Pré-inscription incomplète'), ('P', 'Pré-inscription'), ('V', 'Validé'), ('C', 'Complet'), ('A', 'Annulé')], db_index=True, default='V', max_length=1, verbose_name='État du dossier'),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='nom',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='prenom',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='semaines',
            field=models.ManyToManyField(blank=True, db_index=True, to='tba_camps.Semaine'),
        ),
        migrations.AlterField(
            model_name='stagiaire',
            name='nom',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='stagiaire',
            name='prenom',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='stagiaire',
            name='semaines',
            field=models.ManyToManyField(db_index=True, to='tba_camps.Semaine'),
        ),
    ]
