# Generated by Django 2.1.3 on 2018-12-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tba_camps', '0046_auto_20180225_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='formule',
            name='weekend',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix weekend'),
        ),
        migrations.AlterField(
            model_name='formule',
            name='order',
            field=models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='hebergement',
            name='order',
            field=models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='message',
            name='order',
            field=models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order'),
        ),
    ]
