# Generated by Django 2.1.3 on 2018-12-31 18:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tba_camps', '0048_auto_20181227_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossier',
            name='assurance',
            field=models.DecimalField(choices=[(Decimal('0.00'), "Pas d'assurance"), (Decimal('8.00'), 'Mini-assurance (8€)'), (Decimal('20.00'), 'Maxi-assurance (20€)')], decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Assurance annulation'),
        ),
        migrations.AlterField(
            model_name='formule',
            name='taxe',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Contribution ménage'),
        ),
    ]
