# Generated by Django 2.1.3 on 2019-01-08 00:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tba_camps', '0050_auto_20190105_2354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dossier',
            name='assurance',
        ),
        migrations.RemoveField(
            model_name='formule',
            name='affiche_assurance',
        ),
        migrations.RemoveField(
            model_name='formule',
            name='affiche_mode',
        ),
        migrations.AddField(
            model_name='stagiaire',
            name='assurance',
            field=models.DecimalField(choices=[(Decimal('0.00'), "Pas d'assurance"), (Decimal('8.00'), 'Mini-assurance (8€)'), (Decimal('20.00'), 'Maxi-assurance (20€)')], decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Assurance annulation'),
        ),
    ]
