# Generated by Django 2.1.3 on 2019-08-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tba_camps', '0051_auto_20190108_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='cafno',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name="Numéro d'allocataire"),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='caf',
            field=models.CharField(choices=[('N', 'Non'), ('C', 'CAF'), ('V', 'VACAF')], default='N', max_length=1, verbose_name="Je bénéficie d'une aide CAF ou VACAF"),
        ),
    ]
