# Generated by Django 3.0.1 on 2019-12-28 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tba_camps', '0053_backpack'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backpack',
            options={'verbose_name': 'sac à dos', 'verbose_name_plural': 'sacs à dos'},
        ),
    ]
