# Generated by Django 3.0.1 on 2019-12-28 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tba_camps', '0054_auto_20191228_0141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reversible',
            fields=[
                ('taille', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Taille')),
                ('min_stature', models.IntegerField(null=True, verbose_name='Stature min (cm)')),
                ('max_stature', models.IntegerField(null=True, verbose_name='Stature max (cm)')),
                ('age', models.CharField(blank=True, max_length=6, null=True, verbose_name='Age (ans)')),
            ],
        ),
    ]
