# Generated by Django 3.0.1 on 2020-01-08 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tba_camps', '0058_auto_20191228_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backpack',
            name='numero',
            field=models.CharField(blank=True, max_length=5, verbose_name='Numéro'),
        ),
    ]
