# Generated by Django 3.0.1 on 2021-01-27 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tba_camps', '0060_auto_20210114_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagiaire',
            name='nom_parrain',
            field=models.CharField(blank=True, help_text='NOM Prénom', max_length=255, verbose_name='Je suis parrainé par'),
        ),
        migrations.AlterField(
            model_name='stagiaire',
            name='noms_parraines',
            field=models.TextField(blank=True, help_text='NOMS Prénoms, plusieurs noms possibles', verbose_name='Je parraine'),
        ),
        migrations.CreateModel(
            name='Towel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(blank=True, max_length=15, verbose_name='Prénom')),
                ('numero', models.CharField(blank=True, max_length=5, verbose_name='Numéro')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tba_camps.Dossier')),
            ],
            options={
                'verbose_name': 'serviette',
                'verbose_name_plural': 'serviettes',
            },
        ),
    ]
