# Generated by Django 3.0.1 on 2021-02-01 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tba_camps', '0061_auto_20210128_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='towel',
            name='color',
            field=models.CharField(choices=[('ciel', 'Bleu ciel'), ('blanc', 'Blanc')], default='blanc', max_length=20, verbose_name='Couleur'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stagiaire',
            name='noms_parraines',
            field=models.TextField(blank=True, help_text='NOMS Prénoms, plusieurs noms possibles. Ce doit être un NOUVEAU stagiaire, donc jamais venu à TBA Superdévoluy.', verbose_name='Je parraine'),
        ),
    ]
