# Generated by Django 4.0 on 2022-01-29 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tba_camps', '0063_stagiaire_arrivee'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagiaire',
            name='pass_covid',
            field=models.BooleanField(default=False, verbose_name='Pass sanitaire reçu'),
        ),
    ]
