# Generated by Django 4.2.7 on 2023-12-07 00:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tba_camps", "0064_stagiaire_pass_covid"),
    ]

    operations = [
        migrations.AddField(
            model_name="stagiaire",
            name="regime",
            field=models.CharField(
                blank=True,
                help_text="Décrivez les allergies ou tout régime alimentaires du stagiaire.",
                max_length=1023,
                verbose_name="lequel?",
            ),
        ),
    ]
