# Generated by Django 4.2.7 on 2023-12-08 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tba_camps", "0065_stagiaire_regime"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="formule",
            name="affiche_navette",
        ),
        migrations.RemoveField(
            model_name="formule",
            name="affiche_train",
        ),
        migrations.RemoveField(
            model_name="stagiaire",
            name="navette_a",
        ),
        migrations.RemoveField(
            model_name="stagiaire",
            name="navette_r",
        ),
        migrations.RemoveField(
            model_name="stagiaire",
            name="train",
        ),
        migrations.AlterField(
            model_name="stagiaire",
            name="regime",
            field=models.CharField(
                blank=True,
                max_length=1023,
                verbose_name="Allergie ou régime alimentaire",
            ),
        ),
        migrations.CreateModel(
            name="Transport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="Description"),
                ),
                ("depart", models.CharField(max_length=255, verbose_name="Départ")),
                ("arrivee", models.CharField(max_length=255, verbose_name="Arrivée")),
                (
                    "prix",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Prix"
                    ),
                ),
                ("formules", models.ManyToManyField(to="tba_camps.formule")),
            ],
        ),
        migrations.AddField(
            model_name="stagiaire",
            name="aller",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="aller",
                to="tba_camps.transport",
            ),
        ),
        migrations.AddField(
            model_name="stagiaire",
            name="retour",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="retour",
                to="tba_camps.transport",
            ),
        ),
    ]
