# Generated by Django 4.2.7 on 2024-02-05 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tba_camps", "0067_transportretour_alter_stagiaire_retour"),
    ]

    operations = [
        migrations.CreateModel(
            name="Short",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "equipe",
                    models.CharField(
                        choices=[
                            ("sanb", "San Antonio Spurs noir"),
                            ("sanw", "San Antonio Spurs blanc"),
                            ("chir", "Chicago Bulls rouge"),
                            ("lalp", "Los Angeles Lakers violet"),
                            ("laly", "Los Angeles Lakers jaune"),
                            ("gsww", "Golden State Warrios blanc"),
                            ("bscg", "Boston Celtics vert"),
                            ("bscw", "Boston Celtics blanc"),
                            ("nykb", "New York Knicks bleu"),
                        ],
                        max_length=40,
                        verbose_name="Équipe",
                    ),
                ),
                (
                    "taille",
                    models.CharField(
                        choices=[
                            ("4XS", "4XS"),
                            ("3XS", "3XS"),
                            ("2XS", "2XS"),
                            ("XS", "XS"),
                            ("S", "S"),
                            ("M", "M"),
                            ("L", "L"),
                            ("XL", "XL"),
                            ("2XL", "2XL"),
                            ("3XL", "3XL"),
                        ],
                        max_length=4,
                        verbose_name="Taille",
                    ),
                ),
                (
                    "numero",
                    models.CharField(blank=True, max_length=2, verbose_name="Numéro"),
                ),
                (
                    "dossier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tba_camps.dossier",
                    ),
                ),
            ],
            options={
                "verbose_name": "short",
                "verbose_name_plural": "shorts",
            },
        ),
        migrations.CreateModel(
            name="Maillot",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "equipe",
                    models.CharField(
                        choices=[
                            ("sanb", "San Antonio Spurs noir"),
                            ("sanw", "San Antonio Spurs blanc"),
                            ("chir", "Chicago Bulls rouge"),
                            ("lalp", "Los Angeles Lakers violet"),
                            ("laly", "Los Angeles Lakers jaune"),
                            ("gsww", "Golden State Warrios blanc"),
                            ("bscg", "Boston Celtics vert"),
                            ("bscw", "Boston Celtics blanc"),
                            ("nykb", "New York Knicks bleu"),
                        ],
                        max_length=40,
                        verbose_name="Équipe",
                    ),
                ),
                (
                    "taille",
                    models.CharField(
                        choices=[
                            ("4XS", "4XS"),
                            ("3XS", "3XS"),
                            ("2XS", "2XS"),
                            ("XS", "XS"),
                            ("S", "S"),
                            ("M", "M"),
                            ("L", "L"),
                            ("XL", "XL"),
                            ("2XL", "2XL"),
                            ("3XL", "3XL"),
                        ],
                        max_length=4,
                        verbose_name="Taille",
                    ),
                ),
                (
                    "prenom",
                    models.CharField(blank=True, max_length=15, verbose_name="Prénom"),
                ),
                (
                    "numero",
                    models.CharField(blank=True, max_length=2, verbose_name="Numéro"),
                ),
                (
                    "dossier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tba_camps.dossier",
                    ),
                ),
            ],
            options={
                "verbose_name": "maillot",
                "verbose_name_plural": "maillots",
            },
        ),
        migrations.CreateModel(
            name="Complet",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "equipe",
                    models.CharField(
                        choices=[
                            ("sanb", "San Antonio Spurs noir"),
                            ("sanw", "San Antonio Spurs blanc"),
                            ("chir", "Chicago Bulls rouge"),
                            ("lalp", "Los Angeles Lakers violet"),
                            ("laly", "Los Angeles Lakers jaune"),
                            ("gsww", "Golden State Warrios blanc"),
                            ("bscg", "Boston Celtics vert"),
                            ("bscw", "Boston Celtics blanc"),
                            ("nykb", "New York Knicks bleu"),
                        ],
                        max_length=40,
                        verbose_name="Équipe",
                    ),
                ),
                (
                    "taille",
                    models.CharField(
                        choices=[
                            ("4XS", "4XS"),
                            ("3XS", "3XS"),
                            ("2XS", "2XS"),
                            ("XS", "XS"),
                            ("S", "S"),
                            ("M", "M"),
                            ("L", "L"),
                            ("XL", "XL"),
                            ("2XL", "2XL"),
                            ("3XL", "3XL"),
                        ],
                        max_length=4,
                        verbose_name="Taille",
                    ),
                ),
                (
                    "prenom",
                    models.CharField(blank=True, max_length=15, verbose_name="Prénom"),
                ),
                (
                    "numero",
                    models.CharField(blank=True, max_length=2, verbose_name="Numéro"),
                ),
                (
                    "dossier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tba_camps.dossier",
                    ),
                ),
            ],
            options={
                "verbose_name": "ensemble maillot + short",
                "verbose_name_plural": "ensembles maillot + short",
            },
        ),
        migrations.CreateModel(
            name="Casquette",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "equipe",
                    models.CharField(
                        choices=[
                            ("sanb", "San Antonio Spurs noir"),
                            ("sanw", "San Antonio Spurs blanc"),
                            ("sano", "San Antonio Spurs orange"),
                            ("chir", "Chicago Bulls rouge"),
                            ("chib", "Chicago Bulls noir"),
                            ("laly", "Los Angeles Lakers jaune"),
                            ("gswb", "Golden State Warrios bleu"),
                            ("gswy", "Golden State Warrios jaune"),
                            ("bscg", "Boston Celtics vert"),
                            ("bscw", "Boston Celtics blanc"),
                            ("nykb", "New York Knicks bleu"),
                            ("nyko", "New York Knicks orange"),
                        ],
                        max_length=40,
                        verbose_name="Équipe",
                    ),
                ),
                (
                    "dossier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tba_camps.dossier",
                    ),
                ),
            ],
            options={
                "verbose_name": "casquette",
                "verbose_name_plural": "casquettes",
            },
        ),
    ]
