# Generated by Django 5.1.4 on 2024-12-31 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tba_camps', '0068_short_maillot_complet_casquette'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casquette',
            name='equipe',
            field=models.CharField(choices=[('sanb', 'San Antonio Spurs noir'), ('sanw', 'San Antonio Spurs blanc'), ('chir', 'Chicago Bulls rouge'), ('chib', 'Chicago Bulls noir'), ('gswb', 'Golden State Warrios bleu'), ('gswy', 'Golden State Warrios jaune'), ('nykb', 'New York Knicks bleu'), ('dalb', 'Dallas Mavericks bleu'), ('laly', 'Los Angeles Lakers jaune'), ('bscg', 'Boston Celtics vert'), ('bscw', 'Boston Celtics blanc')], max_length=40, verbose_name='Équipe'),
        ),
        migrations.AlterField(
            model_name='complet',
            name='equipe',
            field=models.CharField(choices=[('sanb', 'San Antonio Spurs noir'), ('sanw', 'San Antonio Spurs blanc'), ('chir', 'Chicago Bulls rouge'), ('gsww', 'Golden State Warrios blanc'), ('nykb', 'New York Knicks bleu'), ('dalb', 'Dallas Mavericks bleu'), ('lalp', 'Los Angeles Lakers violet'), ('laly', 'Los Angeles Lakers jaune'), ('bscg', 'Boston Celtics vert'), ('bscw', 'Boston Celtics blanc')], max_length=40, verbose_name='Équipe'),
        ),
        migrations.AlterField(
            model_name='maillot',
            name='equipe',
            field=models.CharField(choices=[('sanb', 'San Antonio Spurs noir'), ('sanw', 'San Antonio Spurs blanc'), ('chir', 'Chicago Bulls rouge'), ('gsww', 'Golden State Warrios blanc'), ('nykb', 'New York Knicks bleu'), ('dalb', 'Dallas Mavericks bleu'), ('lalp', 'Los Angeles Lakers violet'), ('laly', 'Los Angeles Lakers jaune'), ('bscg', 'Boston Celtics vert'), ('bscw', 'Boston Celtics blanc')], max_length=40, verbose_name='Équipe'),
        ),
        migrations.AlterField(
            model_name='short',
            name='equipe',
            field=models.CharField(choices=[('sanb', 'San Antonio Spurs noir'), ('sanw', 'San Antonio Spurs blanc'), ('chir', 'Chicago Bulls rouge'), ('gsww', 'Golden State Warrios blanc'), ('nykb', 'New York Knicks bleu'), ('dalb', 'Dallas Mavericks bleu'), ('lalp', 'Los Angeles Lakers violet'), ('laly', 'Los Angeles Lakers jaune'), ('bscg', 'Boston Celtics vert'), ('bscw', 'Boston Celtics blanc')], max_length=40, verbose_name='Équipe'),
        ),
    ]
